In [70]:
import sys
import numpy as np
sys.path
sys.path.append('../src')
from XH1 import *

In [71]:
data    = np.array([[-1],[-1],[0],[1],[1],[2],[2],[2],[2],[3],[4],[4],[5],[5],[6],[6],[6],[6]])
weights = np.array([ [1], [1],[0],[1],[1],[2],[2],[2],[2],[3],[4],[4],[5],[5],[6],[6],[6],[6]])

In [72]:
a = np.hstack([data, weights])
a[(a[:,0]<2) & (a[:,0]>0)]

array([[1, 1],
       [1, 1]])

In [73]:
h1 = XH1('h1', 5, 0, 5)
h2 = XH1('h2', 5, 0, 5)

In [74]:
h1.Fill(data)
h2.Fill(data, weights)

NameError: name 'data' is not defined

In [59]:
h1.hist

array([2., 1., 2., 4., 1., 4., 4.])

In [60]:
h1.errors

array([1.41421356, 1.        , 1.41421356, 2.        , 1.        ,
       2.        , 2.        ])

In [51]:
h2.hist

array([ 2.,  0.,  2.,  8.,  3., 18., 24.])

In [61]:
h2.errors

array([ 1.41421356,  0.        ,  1.41421356,  4.        ,  3.        ,
       12.        ])

In [31]:
h3 = h2 + h1

In [32]:
h3.hist

array([ 4.,  1.,  4., 12.,  4., 22., 28.])

In [33]:
(h1*h2).hist

array([ 4.,  0.,  4., 32.,  3., 72., 96.])

In [34]:
(h1/h2).hist

/Users/Alpha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:103: RuntimeWarning: divide by zero encountered in true_divide


array([1.        ,        inf, 1.        , 0.5       , 0.33333333,
       0.22222222, 0.16666667])

In [35]:
h1.Divide(h2,-1).hist

/Users/Alpha/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:80: RuntimeWarning: divide by zero encountered in true_divide


array([-1.        ,        -inf, -1.        , -0.5       , -0.33333333,
       -0.22222222, -0.16666667])

In [36]:
h1.bin_edges

array([0., 1., 2., 3., 4., 5.])

In [37]:
h1.GetBinContent(0)

-1.0

In [38]:
h1.bin_edges

array([0., 1., 2., 3., 4., 5.])

In [39]:
h1.GetBinContentByEdge(0)

-1.0